proxy-providers:
  Airport1:
    url: "URL"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: Direct

#########################全局设置##########################
